name_or_path: ../../../models/pythia-6.9b
tokenizer_name_or_path: ../../../models/pythia-6.9b
archive: null
block_name: GPTNeoXLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16